### ISSUE TITLE
Customizable bookmarked Folders

### ISSUE THREAD

**Issue by fux0r2009** [Secure-File-Manager/Secure-File-Manager#14]
hi @Alfavio 

One think that would be good is to make some bookmarked Folders or quick access folders available to the user so he can quickly jump to the bookmarked destinations instead of having to always navigate from the base folder all the way to his destination.

the bookmarks could be proposed as a side menu with the name of the destinations for example as it would make the access super fast.  

best regards

**Comment by Alfavio** [comment]
Hi @fux0r2009 again! For this purpose you can use home folder. You can set optional folder as home folder from the menu and then you can easily access this folder with home icon in the menu.

<img alt="Home preview" src="https://i.postimg.cc/SszYY9cv/screenshot-nimbus-capture-2021-03-01-18-12-30.png" width="50%">

**Comment by fux0r2009** [comment]
> Hi @fux0r2009 again! For this purpose you can use home folder. You can set optional folder as home folder from the menu and then you can easily access this folder with home icon in the menu.
> 
> <img alt="Home preview" width="50%" src="https://camo.githubusercontent.com/d8d3ce252cc0d0d6026b6cceaa487a50ad8a4804587b564f74466e4403f3e083/68747470733a2f2f692e706f7374696d672e63632f53737a59593963762f73637265656e73686f742d6e696d6275732d636170747572652d323032312d30332d30312d31382d31322d33302e706e67">

Hi @Alfavio thanks for your answer, yes I am aware of the home folder feature but unfortunately it only works if you have a single destination or path... so to use multiple places you need a bookmark system like the home feature but for multiple places!

**Comment by Alfavio** [comment]
@fux0r2009 And the favorites folders feature is not sufficient for this? It uses multiple folders which are easily accessible from the menu.

**Comment by fux0r2009** [comment]
@Alfavio Again by bad you are right again sorry I wasn't paying attention 👍 please close this issue thanks :)

**Comment by fux0r2009** [comment]
@Alfavio the only minor adjustment I may suggest is that to access the favorites you have to go home first and then click on the start Icon so I believe it could be better to make the favorite folders available on a left side menu of the app with just the name of the folders (not the whole path) so the user can access them from anywhere without having to go to home first but it's a minor detail so it up to you dear @Alfavio anyway again thanks for the replay about the favorite feature !!

**Comment by Alfavio** [comment]
Yes, it would be better to be accessible with one tap, but on another hand, lots of icons are not desirable. I am excited for your enthusiasm and good suggestions focused on the user experience. If you have another feature request, please open a new issue. Also, if you know programming - contributions, and pull requests are welcome.
