### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by 2008201** [Secure-File-Manager/Secure-File-Manager#21]
Hello.  the app cannot be uninstalled.

**Comment by Alfavio** [comment]
Hi @2008201. Please, can you describe to me in more detail, how to reproduce your problem?

**Comment by 2008201** [comment]
Hello.  there were problems uninstalling the app.  I've tried different options.  Restart, clear cache, delete data.  I have Android 10 on my device.  The app has now been uninstalled, I moved the app to the trash.  Today the app could no longer be found.  Thanks.

**Comment by 2008201** [comment]
Hello.  there were problems uninstalling the app.  I've tried different options.  Restart, clear cache, delete data.  I have Android 10 on my device.  The app has now been uninstalled, I moved the app to the trash.  Today the app could no longer be found.  Thanks.

Am April 14, 2021 9:22:10 AM UTC schrieb Alfavio ***@***.***>:
>Hi @2008201. Please, can you describe to me in more detail, how to
>reproduce your problem?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Secure-File-Manager/Secure-File-Manager/issues/21#issuecomment-819371901

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mannp** [comment]
I have the same problem here. I installed the app and did some basic config.

Closed the app and went to uninstall.

The app crashes my package manager and I  am unable to uninstall your app.

No issues before installing this app :-/

Any thoughts on how I may now remove it please?

I don't have root.

Thanks.
