### ISSUE TITLE
No camera or video icon

### ISSUE THREAD

**Issue by MembershipExcel** [Secure-File-Manager/Secure-File-Manager#22]
As say in the introduction, there should be an icon for video and camera but i can't see one

**Comment by Alfavio** [comment]
Hi @MembershipExcel. This icon are shown only if your device has camera. Which device you are using?

**Comment by MembershipExcel** [comment]
> Hi @MembershipExcel. This icon are shown only if your device has camera. Which device you are using?

Android Phone LG Velvet 5G

**Comment by Alfavio** [comment]
Thank you for the bug report! I fixed it. The new version will be soon available at Google Play and F-Droid. Please, let me know if the media icons works correctly on your device after you install the new version.
