### ISSUE TITLE
Idea: the ability to hide folders/files names that starts with a dot

### ISSUE THREAD

**Issue by blackandyellowgecko** [Secure-File-Manager/Secure-File-Manager#24]
Currently, all folders and files names that starts with a dot are shown and there's no way to hide them.

**Comment by Alfavio** [comment]
Hi @blackandyellowgecko! Thank you for the feature request. I'm not sure, what do you mean by "a period", can you please describe it in more detail?

**Comment by blackandyellowgecko** [comment]
whoops, I meant dot. Sorry.

**Comment by Alfavio** [comment]
@blackandyellowgecko Currently, there is an available feature to hide folders or files in the hidden storage. If I also add your described feature, this will be confusing for the user what _"hide"_ means. For this reason, I don't plan to add this feature.
