### ISSUE TITLE
Searching for files freezes and crashes app on android 10

### ISSUE THREAD

**Issue by ZOASR** [Secure-File-Manager/Secure-File-Manager#29]
searching for any keyword crashes app immediatly

**Comment by Alfavio** [comment]
Hi @ZOASR. Thank you for your bug report. I fixed it and also improve the search feature. Changes will be included in the next release.

**Comment by ZOASR** [comment]
> Hi @ZOASR. Thank you for your bug report. I fixed it and also improve the search feature. Changes will be included in the next release.

No problem, Glad that it's fixed!
