### ISSUE TITLE
Set Manual Transformation Rounds

### ISSUE THREAD

**Issue by Github-com-foss** [Secure-File-Manager/Secure-File-Manager#32]
Its prevent from dictionary attack. We manually set eg: 60000 to 100000..........or above. It hardened the encryption of the file. File is more secure while share to others or file safe in while unhidden.
Keepassdx app already have this feature 
Keepassdx app> settings> security> transformation rounds > set manually
https://github.com/Kunzisoft/KeePassDX

**Comment by Alfavio** [comment]
Hi @Github-com-foss. Thank you for your feature request. For file encryption, the app currently uses the key from the Android key store. More information about file encryption is available in the [FAQ](https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions#how-are-my-files-encrypted). Transformation rounds are only for passwords, not keys. The password-based encryption was already requested #20. If I will add password-based encryption, I also can add transformation rounds to the app settings. Currently, the app uses Argon2 as the hash algorithm for passwords. For advanced users is desirable to add Argon2 parameter setup to the app setting. I created for that new issue #34. More information about password storing is also available in the [FAQ](https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions#how-do-you-store-my-password).
