### ISSUE TITLE
[Proposal] French translation

### ISSUE THREAD

**Issue by Ilithy** [Secure-File-Manager/Secure-File-Manager#35]
Hi; 
I would like to know if you accept a PR of translation of the application in French language, I do not know if this requires modifications in the interface...

 I have already translated the String.xml file (the only one that seems to need a translation)
 I can perform a PR or provide the xml file directly, or neither, of course. ;-)

Friendly

**Comment by Alfavio** [comment]
Hi @Ilithy. Thank you for your translation. This is awesome :heart: thank you! PR would be better I think.

**Comment by Alfavio** [comment]
@Ilithy #37 mas merged. Thank you again!

**Comment by Ilithy** [comment]
Thanks to you, I remain at your disposal

**Comment by Alfavio** [comment]
@Ilithy If you want to be notified about changes in translation and keep the French language up to date, you can set [file watcher.](https://app.github-file-watcher.com/) for the main [string.xml](https://github.com/Secure-File-Manager/Secure-File-Manager/blob/master/app/src/main/res/values/strings.xml).

**Comment by Ilithy** [comment]
@Alfavio Excellent idea, thank you, indeed, it will facilitate the follow-up of the translation

**Comment by Alfavio** [comment]
@Ilithy I added you to [README.md](https://github.com/Secure-File-Manager/Secure-File-Manager/blob/master/README.md) as thanks. If you didn't want it, I can delete it. Also, I add the app translation to the [Crowdin](https://crowdin.com/project/secure-file-manager) tool for easier translation.

**Comment by Ilithy** [comment]
Thank you very much, it's very nice, if it bothers you (it makes the readme heavier), you can remove it, it's not a problem :-) Great idea to use Crowdin, it will make it easier to add new languages.
