### ISSUE TITLE
Google Play rejected new releases

### ISSUE THREAD

**Issue by Alfavio** [Secure-File-Manager/Secure-File-Manager#36]
Hi, currently I have a problem with publishing app updates in Google Play. They rejected new updates 4 times. First time _(v0.1.5-beta)_ as a reason they said:

[answer1.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6406879/answer1.pdf)

After that, I contacted Google support and they answered:

[answer2.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6406881/answer2.pdf)
[Secure File Manager Beta.png](https://user-images.githubusercontent.com/5478075/116727800-54307980-a9e5-11eb-87f4-1e415fb45fea.png)

I added [GOOGLE_PLAY_PUBLISHER.md](https://github.com/Secure-File-Manager/Secure-File-Manager/commit/e2ee2d14501f4257d92cef37006b696d3d2ebac0#diff-afa133b51246e64e1570d0093ad9ffd6166478c45731ca74105cbb2c520e7642) file to the root of the app source code and change the app website to the [blob](https://github.com/Secure-File-Manager/Secure-File-Manager/commits/master/GOOGLE_PLAY_PUBLISHER.md) of this file and add a link to this file in the app description in the Google Play Console. After that, I released a new version _(v0.1.6-beta)_ and the app was rejected again. The reason was the same. I contacted the support again and they answered:

[answer3.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6406889/answer3.pdf)

I updated [GOOGLE_PLAY_PUBLISHER.md](https://github.com/Secure-File-Manager/Secure-File-Manager/commit/d3d1dd435179c1318db134858fc86923bd64fc65#diff-afa133b51246e64e1570d0093ad9ffd6166478c45731ca74105cbb2c520e7642), released a new version _(v0.1.7-beta)_ and prayed. The app was rejected again. The reason was the same, but in different words:

[answer4.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6406893/answer4.pdf)
[com securefilemanager app-DeveloperWebsite-49.png](https://user-images.githubusercontent.com/5478075/116728042-aec9d580-a9e5-11eb-9f72-50cb7ac389a3.png)

I updated [GOOGLE_PLAY_PUBLISHER.md](https://github.com/Secure-File-Manager/Secure-File-Manager/commit/632961366d7807a1ddb87c9e26a8b35beb821976#diff-afa133b51246e64e1570d0093ad9ffd6166478c45731ca74105cbb2c520e7642), released a new version (v.0.1.7-beta2) and prayed again. The app was rejected again. The reason was different this time:

[answer5.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6406906/answer5.pdf)

Now, I'm desperate. Please, can anybody help me with this issue? :pray:  I don't understand why the updates were rejected. What can I do?

**Comment by SerjSX** [comment]
Hello, first the problem I see here is that Playstore thinks this is a news app. Please contact them and inform them that this isn't a news app, and change it to "Tools" category.

Second, in the app's description add a link to this github by telling that it's open source. As in:
"This app is free and open-source, no tracking included. You can check the source code here: github link"

**Comment by Ilithy** [comment]
Incomprehensible...
Wouldn't this be related to the permission to read and write on the external storage?

@SerjSX For the category, it is well referenced as tools (on the FR play store anyway);
maybe it could be useful to expand the description of the application, including the data as presented on Github:

Secure File Manager is open source file manager for keeping your files in safe.
This app is for Android 8.0+.

 - Open source
 - Privacy friendly
 - Free
 - No ads
 - No unnecessary permissions

A link to the license of the application (GPL V3) could help... maybe.

Note that on F-Droid the application is not at the latest version (v0.1.7-Beta2) but at version 0.1.6.

**Comment by Alfavio** [comment]
Updates for the F-Droid are [automated](https://gitlab.com/fdroid/fdroiddata/-/commit/bc80a9612906f496d31189e166a3c3731a644cd3) and it took a little bit longer to reflect. 

The app has already set category "Tools" as you can see in the following:
![Screenshot_2021-05-02 Store settings Secure File Manager Beta](https://user-images.githubusercontent.com/5478075/116810474-40e7f000-ab44-11eb-82f6-ddf0cb36b7b1.png)

I'm gonna try to change the description in the next release and we will see if it will help. Or something else if someone comes up with something new.

**Comment by Ilithy** [comment]
> Updates for the F-Droid are [automated](https://gitlab.com/fdroid/fdroiddata/-/commit/bc80a9612906f496d31189e166a3c3731a644cd3) and it took a little bit longer to reflect.

Ok, thanks

**Comment by SerjSX** [comment]
> 
> 
> Incomprehensible...
> Wouldn't this be related to the permission to read and write on the external storage?
> 
> @SerjSX For the category, it is well referenced as tools (on the FR play store anyway);
> maybe it could be useful to expand the description of the application, including the data as presented on Github:
> 
> Secure File Manager is open source file manager for keeping your files in safe.
> This app is for Android 8.0+.
> 
>     * Open source
> 
>     * Privacy friendly
> 
>     * Free
> 
>     * No ads
> 
>     * No unnecessary permissions
> 
> 
> A link to the license of the application (GPL V3)
> [GNU GPL v3 License](https://www.gnu.org/licenses/gpl-3.0.txt)
> could help... maybe.
> 
> Note that on F-Droid the application is not at the latest version (v0.1.7-Beta2) but at version 0.1.6.

Alrighty.



> 
> 
> Updates for the F-Droid are [automated](https://gitlab.com/fdroid/fdroiddata/-/commit/bc80a9612906f496d31189e166a3c3731a644cd3) and it took a little bit longer to reflect.
> 
> The app has already set category "Tools" as you can see in the following:
> ![Screenshot_2021-05-02 Store settings Secure File Manager Beta](https://user-images.githubusercontent.com/5478075/116810474-40e7f000-ab44-11eb-82f6-ddf0cb36b7b1.png)
> 
> I'm gonna try to change the description in the next release and we will see if it will help. Or something else if someone comes up with something new.

@Alfavio weird though in the pdfs you've posted it was talking about "News", yeah try to change the description and etc and see if it works.

**Comment by fux0r2009** [comment]
As long as it is on F-Droid I think a lot of users don't give a dam about play-store :)

**Comment by SerjSX** [comment]
> 
> 
> As long as it is on F-Droid I think a lot of users don't give a dam about play-store :) but I hope you will resolve the issue!

Yes, but Playstore does have more people, so it may get more popular there. But yes, I hope it does get resolved as well. I will start using it once it's out of beta, to prevent any data loss.

**Comment by fux0r2009** [comment]
> > As long as it is on F-Droid I think a lot of users don't give a dam about play-store :) but I hope you will resolve the issue!
> 
> Yes, but Playstore does have more people, so it may get more popular there. But yes, I hope it does get resolved as well. I will start using it once it's out of beta, to prevent any data loss.

I see what you mean and yes it's good to wait for the stable version to be safe... I use the current version for day to day and I am happy with it, no problems so far but I am looking forward to future versions even more with (hopefully) implemented requested features!

**Comment by Alfavio** [comment]
I published the [0.1.8-beta](https://github.com/Secure-File-Manager/Secure-File-Manager/releases/tag/v0.1.8-beta) version to Google Play. I also changed the description of the app as you recommend. Now the new release is in review. I will inform you about Google's response. Now lets hope :crossed_fingers:.

**Comment by SerjSX** [comment]
> 
> 
> I published the [0.1.8-beta](https://github.com/Secure-File-Manager/Secure-File-Manager/releases/tag/v0.1.8-beta) version to Google Play. I also changed the description of the app as you recommend. Now the new release is in review. I will inform you about Google's response. Now lets hope 🤞.

Cool, I hope it'll get accepted.

**Comment by Ilithy** [comment]
@Alfavio: Thank you for all your efforts

 @SerjSX: I totally agree

**Comment by Alfavio** [comment]
The update was rejected :confused:

[output.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6416773/output.pdf)
[com securefilemanager app-AppWebsite-160.png](https://user-images.githubusercontent.com/5478075/116914563-2f3d4000-ac4b-11eb-84bd-54985182f4d5.png)

**Comment by SerjSX** [comment]
> The update was rejected 😕
> 
> [output.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6416773/output.pdf)
> [com securefilemanager app-AppWebsite-160.png](https://user-images.githubusercontent.com/5478075/116914563-2f3d4000-ac4b-11eb-84bd-54985182f4d5.png)
@Alfavio 
It says:
We found an issue in the following area(s):
App website: Please see attached screenshot
com.securefilemanager.app-AppWebsite-160.png

What's the screenshot? And why does it say "News" policy? 

Afterall if nothing works contact their "policy support team" maybe they can explain it in more detail.

**Comment by Alfavio** [comment]
@SerjSX I already contacted support. We will see what will they answer. I will inform you about response.

**Comment by SerjSX** [comment]
> @SerjSX I already contacted support. We will see what they will answer. I will inform you about response.

Alrighty 👌🏻

**Comment by Alfavio** [comment]
They responded, but didn't answer my questions.

[output.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6422480/output.pdf)

**Comment by SerjSX** [comment]
> They responded, but didn't answer my questions.
> 
> [output.pdf](https://github.com/Secure-File-Manager/Secure-File-Manager/files/6422480/output.pdf)

@Alfavio Then ignore and remove the app from Playstore I guess, what's the point 🤷🏻‍♂️ 
If you want make a thread on XDA Forums, if it goes viral then more people will look into it. Keep it on F-Droid and Github, Google's loss 🤷🏻‍♂️

**Comment by Alfavio** [comment]
I unpublished the app from the Google play until this issue will be resolved.

**Comment by SerjSX** [comment]
> I unpublished the app from the Google play until this issue will be resolved.

Cool, that's probably best for now.
