### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by Alfavio** [Secure-File-Manager/Secure-File-Manager#4]
As requested in the #1

**Comment by TheEvilSkeleton** [comment]
A black theme would be nice as well.

**Comment by fux0r2009** [comment]
> A black theme would be nice as well.

Absolutely

**Comment by Github-com-foss** [comment]
Pls Add amoled black (pure black)

**Comment by Alfavio** [comment]
As requested, I added a dark theme to the app. I extracted dark color from the [vantablack](https://en.wikipedia.org/wiki/Vantablack), so all AMOLED displays will be happy. Dark theme will be available in the next release of the app. For impatient there is a preview:

<img alt="Dark theme preview" src="https://user-images.githubusercontent.com/5478075/115964113-23eb6580-a523-11eb-9301-95b479113d97.png" width="35%">

**Comment by TheEvilSkeleton** [comment]
This looks really clean!

**Comment by fux0r2009** [comment]
Wonderful !! Thanks @Alfavio

**Comment by Alfavio** [comment]
New version [0.1.7](https://github.com/Secure-File-Manager/Secure-File-Manager/releases/tag/v0.1.7-beta) was released. The new version will be soon available at Google Play and F-Droid.
