### ISSUE TITLE
Impossible to uninstall..

### ISSUE THREAD

**Issue by Danish-Vidar** [Secure-File-Manager/Secure-File-Manager#41]
No matter what I try I can't uninstall the app. 

Phone: Pixel 3a with GrapheneOS. Downloaded from F-Droid v0.1.7-beta.

**Comment by Alfavio** [comment]
Hi @Danish-Vidar. Thank you for the bug report. This is really strange bug. I gonna look at it closer.

Related issues: #27, #21

**Comment by Alfavio** [comment]
@Danish-Vidar It looks like it is an Android-related problem https://github.com/tasks/tasks/issues/1292. I was searching and found that more apps have the same problem. It looks like the [`hasFragileUserData`](https://developer.android.com/guide/topics/manifest/application-element) cause this issue on some Android devices. As a solution, try to use [`adb`](https://developer.android.com/studio/command-line/adb) to uninstall the app. I am sorry about this issue, but I can't influence it.

**Comment by Alfavio** [comment]
@Danish-Vidar I compiled [0.1.8-beta](https://github.com/Secure-File-Manager/Secure-File-Manager/releases/tag/v0.1.8-beta) version without `hasFragileUserData` attribute. It maybe help you to successfully uninstall the app. Please, let me know.
