### ISSUE TITLE
Issue with the app lock

### ISSUE THREAD

**Issue by Ilithy** [Secure-File-Manager/Secure-File-Manager#42]
**Description**
The application lock is not fully functional, and only locks the application under certain conditions.

**System Setup**
Android version: 10
Secure File Manager version: 0.1.6
Origin: F-Droid

**Steps to Reproduce**
1- Launch the application and set the application lock.
2- Quit the application, or put it in the background
3- Relaunch the application.

**Expected Behavior**
Each time the application is put in the background, or completely closed, it locks, and asks for the password, or the biometric authentication to reopen/pass to the foreground

**Actual Behavior**
The application triggers the unlock request only if the user has left the application by clicking twice on the back button (or makes the equivalent gesture)

**Reproducibility**
Always

**Additional Information**

Let me provide a video capture, to facilitate the quick visualization of the problem:
https://drive.google.com/file/d/1yi35Aq85YCGRCfMkm6BenFOrJvXv_Yut/view?usp=drivesdk

**Comment by Alfavio** [comment]
@Ilithy Thank you for opening the issue. It looks like it works as it was designed. The app is locked after several conditions:

- app was quit
- app was locked via the notification
- device was locked
- app was failed _(some app bug)_
- device was booted _(if a device was unexpectedly turned off and the app is in an unlocked state)_

These requirements are designed for a better user experience. I added this to the [FAQ](https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions#how-can-i-lock-the-app).

However, it will be useful to add an option to force to lock the app immediately after putting it in the background. For that, I created a feature request #43.
