### ISSUE TITLE
App Crashes after viewing file properties.

### ISSUE THREAD

**Issue by GlowScarf** [Secure-File-Manager/Secure-File-Manager#44]
I am using the latest beat version (0.1.7-beta2).
I hid a file (video) and then I hold it and viewed it's properties. After that I couldn't do anything nor go back, nor tap OK and in order to fix that I closed the app and I had to kill it's process to open it again and also to use the lock button from notification. If I tried to open it without killing it's process i just couldn't. Tried it again and happened again. Device: Redmi Note 8 Pro (EU) android 10.

**Comment by Alfavio** [comment]
Hi @GlowScarf. Thank you for the bug report. I fixed it. Fix will be included in the next release.

**Comment by GlowScarf** [comment]
> Hi @GlowScarf. Thank you for the bug report. I fixed it. Fix will be included in the next release.

Glad to know.
