### ISSUE TITLE
decryption while the phone is still unlocked

### ISSUE THREAD

**Issue by frasty** [Secure-File-Manager/Secure-File-Manager#45]
Is there a way to ask for a password/biometrics each time I want to decrypt an encrypted file?
I mean if the device is still unlocked, no matter if the app is still running in the background or in the foreground, anyone can decrypt the encrypted file without an authentication request.
Is this how the app is supposed to work or am I missing something?

**Comment by Alfavio** [comment]
Hi @frasty. Thank you for submitting this issue. Currently, there is no way to ask for password/biometrics each time you want to decrypt an encrypted file. For that, I created feature request #46. The lock of the app is described in the [FAQ](https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions#how-can-i-lock-the-app).
