### ISSUE TITLE
Bug : APK not recognized by the file manager

### ISSUE THREAD

**Issue by fux0r2009** [Secure-File-Manager/Secure-File-Manager#47]
The APK file format is not recognized by the app and I can't install them as they show like generic undefined files.

Android : 11 (MIUI 12.0.5 Stable)

**Comment by Alfavio** [comment]
Hi @fux0r2009. Thank you for the bug report. This feature was removed from the app because it requires additional permission. This permission made the app less trustworthy.

Related issue: #23

**Comment by fux0r2009** [comment]
Hi @Alfavio I see, Is there a chance to make that feature available in future builds as I believe many users would rather use this app as a file manager and not just a file encryption app besides the app is open source so there is no trustworthiness gain by removing this feature! So I hope you will reconsider this choice in future releases.

Best regards and thanks for your work as always  :)
