### ISSUE TITLE
Not able to install app on my device

### ISSUE THREAD

**Issue by Thewisem** [Secure-File-Manager/Secure-File-Manager#51]
My device runs the Armeabi v7a architecture. And it seems your app doesn't support that architecture. As it is incompatible to me

**Comment by Alfavio** [comment]
Hi @Thewisem. Thank you for opening the issue. The app should work fine with armeabi-v7a architecture. Please, can you describe in more detail your problem?

**Comment by Thewisem** [comment]
I am using a tablet

**Comment by Alfavio** [comment]
Please, can you upload a screenshot with the error and also describe the source of the app?

**Comment by Thewisem** [comment]
![Screenshot_20210718-202809](https://user-images.githubusercontent.com/74511929/126076650-5b9633ef-d46d-49b2-9e55-5bf5cea770bb.jpg)
Here. And this is github apk

**Comment by Alfavio** [comment]
Please try “Allow installation from unknown resources” for the browser that you are using, or try installing the APK from a build-in file manager.

**Comment by Thewisem** [comment]
It is totally allowed

**Comment by Thewisem** [comment]
Its not compatibe

**Comment by Thewisem** [comment]
In fact even fdroid says its not

**Comment by Thewisem** [comment]
![Screenshot_20210718-212443](https://user-images.githubusercontent.com/74511929/126078259-e929c46c-0201-40f3-b674-75f608c241d2.jpg)
Yeah

**Comment by Alfavio** [comment]
What is the version of Android on your device? This app is for Android 8.0+.

**Comment by Thewisem** [comment]
Oh. Dame. I an 7.1.1 Nougat

**Comment by Thewisem** [comment]
Sorry for disturbing then
