### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by ifdoysoyd7rr7r** [Secure-File-Manager/Secure-File-Manager#52]
Unable to uninstall the app on android 11 samsung m01 
Other app are uninstalling in older way but i cant uninstall it

**Comment by ifdoysoyd7rr7r** [comment]
Sir 
Please help me 
I am trying it from 1 day to uninstall
Share a way to uninstall it

**Comment by ifdoysoyd7rr7r** [comment]
![Screenshot_20210723-175629_One UI Home.jpg](https://user-images.githubusercontent.com/87861092/126782107-3d68690f-477e-496c-85eb-af13e2fc3bb0.jpg)

**Comment by ifdoysoyd7rr7r** [comment]
Dear developer 
I am Waiting for your helps and suggestions

**Comment by ifdoysoyd7rr7r** [comment]
Same issue of uninstalling had occured with osm maps and navigation which i installed from fdroid
But its not uninstalling then i uninstalled it from google play store app
But in case of this app 
this app is not available on google play store 
And not even showing installed in manage apps and device section of play store

**Comment by idlebg** [comment]
I have built the current version from the source code. and there is no issue during uninstallation.
And it even asks: 
![image](https://user-images.githubusercontent.com/50985923/126800697-c27e467d-d160-4723-84c8-a7b247d45a61.png)
:) 
Check your phone uninstaller or use 3rd party soft to clean (cache and data of the app)

**Comment by ifdoysoyd7rr7r** [comment]
> I have built the current version from the source code. and there is no issue during uninstallation.
> And it even asks: 
> ![image](https://user-images.githubusercontent.com/50985923/126800697-c27e467d-d160-4723-84c8-a7b247d45a61.png)
> :) 
> Check your phone uninstaller or use 3rd party soft to clean (cache and data of the app)
> 
> 
> android 11 (s21)

Sir 
I have already cleared  app data 
Even after this it is not uninstalling

**Comment by ifdoysoyd7rr7r** [comment]
![Screenshot_20210723-210949_Settings.jpg](https://user-images.githubusercontent.com/87861092/126806948-1c00e171-4fd7-43af-b4f5-340617c7c1e0.jpg)

**Comment by idlebg** [comment]
do upload the APK you are using and I will test it on several devices. Interested in what might be the problem at your end.
get the ap using apk analyzer or any tool you like and send a link.

**Comment by ifdoysoyd7rr7r** [comment]
> ![Screenshot_20210723-175629_One UI Home.jpg](https://user-images.githubusercontent.com/87861092/126782107-3d68690f-477e-496c-85eb-af13e2fc3bb0.jpg)

Showing same error now also

**Comment by idlebg** [comment]
can you uninstall any other app on your device?

also, any other app that is not in the play store.....
for example something from https://www.f-droid.org/

**Comment by idlebg** [comment]
also go to the package installer 
![image](https://user-images.githubusercontent.com/50985923/126808396-1a6e8143-a162-4326-bb75-0438d585c454.png)
and lead its data and cache too

**Comment by ifdoysoyd7rr7r** [comment]
> also go to the package installer 
> ![image](https://user-images.githubusercontent.com/50985923/126808396-1a6e8143-a162-4326-bb75-0438d585c454.png)
> and clear its data and cache too

Yess 
I just uninstalled just chess 
And its done

**Comment by ifdoysoyd7rr7r** [comment]
But i am unable to uninstall this app 
I have also cleared data of package installer

**Comment by ifdoysoyd7rr7r** [comment]
> But i am unable to uninstall this app 
> I have also cleared data of package installer
> 

![Screenshot_20210723-214236_Settings.jpg](https://user-images.githubusercontent.com/87861092/126811167-6963dda3-f7da-4d7e-8a05-4a13c2356d1d.jpg)

**Comment by idlebg** [comment]
do this please to test your apk
https://github.com/Secure-File-Manager/Secure-File-Manager/issues/52#issuecomment-885730591

**Comment by ifdoysoyd7rr7r** [comment]
https://f-droid.org/packages/com.securefilemanager.app/

Link of this app from where i installed it which is froid

**Comment by ifdoysoyd7rr7r** [comment]
https://ln4.sync.com/dl/1741de9b0#jtgktvqb-y656f3jk-c78k6g65-4yms8kku

Its password is 927252
It is link of apk file which is stored on cloud
Exctracted apk of secure file manager beta

**Comment by ifdoysoyd7rr7r** [comment]
I have sent the app which i have installed (which is unable to uninstall)after extracting it


Why i can't see your app on play store 
If this app is their on play store it will be uninstalled definetly

**Comment by ifdoysoyd7rr7r** [comment]
Reply please !

**Comment by Alfavio** [comment]
Hi @ifdoysoyd7rr7r, I am sorry about this issue. Please check #41 and try to uninstall the app with ADB, or install the app with a version without `hasFragileUserData` attribute and then try to uninstall. Please, let me know if it helped you.

**Comment by ifdoysoyd7rr7r** [comment]
Sorry 
But the version 0.1.8 beta without fragile user data is unable to install

**Comment by ifdoysoyd7rr7r** [comment]
I don't know about adb and how to use it

**Comment by ifdoysoyd7rr7r** [comment]
I think it will be a great help to me if this app is present on play store (it is not present now on p.s. so i wish u upload their on p.s. for few moments)

Because it is sure that if their on play store your app shows installed 
Then i can surely UNINSTALL it.

**Comment by ifdoysoyd7rr7r** [comment]
Please reply !

**Comment by ifdoysoyd7rr7r** [comment]
I am Still waiting!!!!!!

**Comment by ifdoysoyd7rr7r** [comment]
Still waiting.......

**Comment by Alfavio** [comment]
@ifdoysoyd7rr7r Google Play rejected last updates #36. [Here](https://developer.android.com/studio/command-line/adb)  is an official tutorial on how to use ADB.

ADB command to delete the app:

`adb uninstall com.securefilemanager.app`

**Comment by ifdoysoyd7rr7r** [comment]
Thanks

**Comment by ifdoysoyd7rr7r** [comment]
And sorry i don't even know basic coding 
I have never used adb
Even i don't have laptop/ desktop

**Comment by Alfavio** [comment]
Closing due inactivity.
