### ISSUE TITLE
Transfer files/folders to/from Mac/PC

### ISSUE THREAD

**Issue by degoogled** [Secure-File-Manager/Secure-File-Manager#55]
I can't seem to transfer files/folders to/from my Mac. I have Android File Transfer and Phone Manager for Android, but neither can see the hidden file. Could you issue Mac/PC app that can manage data to/from the phone? Thanks

**Comment by Alfavio** [comment]
Hi @degoogled! This works as expected. Hidden files should don't be accessible outside the app. To transfer files/folders to a desktop PC you must first expose hidden files/folders outside hidden storage _(move to outside hidden storage)._
