### ISSUE TITLE
Where are hidden files and how to unhide

### ISSUE THREAD

**Issue by michuvon** [Secure-File-Manager/Secure-File-Manager#57]
I have hidden some files but I'm unable to find a option to unhide them.
I can see them, but not access, if I want to hide another file, then they appear in the hidden file list.

Is there a way to unhide, or do I need to go to a special location on the FS?
Or is the feature missing?

**Comment by michuvon** [comment]
🙈 got it.

on the initial screen tap on 'internal' (top left, where it shows the file path) there you can switch between hidden and normal 'internal' storage.

#feature-request : add this info in the app's tutorial.

**Comment by michuvon** [comment]
Maybe it's there alread, and I missed it?
if not, make a page where it says: ''tap here, to see your hidden files''

**Comment by Alfavio** [comment]
Something similar is already in the tutorial.

<img src="https://user-images.githubusercontent.com/5478075/148688087-b7ae07b4-0d52-4d49-b768-c5296dc37e1b.jpeg" width="300" />
