### ISSUE TITLE
Question for FAQ: Is the thumbnail cache also encrypted?

### ISSUE THREAD

**Issue by OskarMuller** [Secure-File-Manager/Secure-File-Manager#58]
Hi,

many thanks for your nice app! :)

I have a question, which I didn't found in the FAQ: Is the thumbnail cache also encrypted?

**Comment by Alfavio** [comment]
Hi @OskarMuller. Thank you! No, thumbnail cache is not encrypted. It is managed by [glide library](https://github.com/bumptech/glide). Because of that, you can disable thumbnails or remove thumbnail cache from the settings.

**Comment by OskarMuller** [comment]
OK, thank you for the information!
