### ISSUE TITLE
It doesn't start on android 11

### ISSUE THREAD

**Issue by BlutRipHub** [Secure-File-Manager/Secure-File-Manager#59]
The application after the update does not start on android 11, after opening it hangs on the splash screen and does not go beyond the first message about the need to access the files. Everything worked in the previous version.

**Comment by Ilithy** [comment]
hi, can you provide more information?
the program was installed from what source?
which version of the application?
what device are you using?
Thanks
Because personally, on my two devices (oneplus 6 under oxygenOS 11.1.2.2 - Android 11 and a Pixel 6 pro under GrapheneOS build SQ1D.211205.017.2022011009 - Android 12) the application works perfectly.

**Comment by BlutRipHub** [comment]
Hi, version 0.1.9, from F-Droid, Lineage 18.1 Unofficial on ZTE Blade A7 2020 3/64 GB. Version 0.1.8 is working stably. The latest beta version does not run at all.

13 января 2022 г. 11:10:43 UTC, Ilithy ***@***.***> пишет:

**Comment by Alfavio** [comment]
Hi @BlutRipHub. Thank you for your bug report. It looks like it works also on my device with Android 12. Maybe there is an issue with your device. The changes in the 0.1.9 should not break the app. Please try following to resolve this issue:

- try clear app data _(**important**: this will remove all your encrypt keys and also hidden files, so make this only if you can loose your data!)_
- try install the app from [github](https://github.com/Secure-File-Manager/Secure-File-Manager/releases/tag/v0.1.9-beta).
- try uninstall the app _(check option to keep app data if you have encrypted or hidden files)_ and install it again.

**If you have encrypted or hidden important files in the app, then install version 0.1.8 and make backup before steps above.**

@Ilithy Thank you for participating.

**Comment by Alfavio** [comment]
No answer and nobody else complains so I'm closing the issue.
