### ISSUE TITLE
How to unhide files?

### ISSUE THREAD

**Issue by ShinyEmeraldGames** [Secure-File-Manager/Secure-File-Manager#66]
Hello,
I have hidden several files with the app and now I'm wondering how to unhide them. If I create a new file and hide it, it shows me the other hidden files in that folder, but how can I umhide these files, so they show up in my regular storage?

Thanks, otherwise great app, the encryption works flawlessly :-)

**Comment by Alfavio** [comment]
Hi @ShinyEmeraldGames. Thank you.

Answer from #56 issue:
> You can go to the hidden storage an then long press to the file that you want to unhide. After that, you can unhide selected file by click on the eye icon, or selecting "move to..." from the menu.

There is maybe user experience issue, because you is the second one with the same question. Have you any idea, how to make _"unhide"_ feature better from user experience prospective?
