### ISSUE TITLE
Cant able to access Unhided files 

### ISSUE THREAD

**Issue by itsmeBond007** [Secure-File-Manager/Secure-File-Manager#69]
I have hidden some image files this morning ,1 hour later i have decided to unhide those image files after successfully unhiding those image files ,strange i cant able to access those image files
 
"Error message : cannot open the file "

what the hell really ,,. please fix this bug asap
 
This app needs lot of bugs to be fixed , and one more bug is  cant able to take screenshot when i have switch off the block screenshot option also( i am aware of secure fact when i have switched it off also) really terrible these bugs need to be fixed asap

**Comment by Alfavio** [comment]
Hi @itsmeBond007! Thank your bugs reporting.

In case of unable to access the unhidden file, please can you add some more additional information to reproduce your issue?

In case of unable to take a screenshot, does the issue persist after quitting the application and opening it again?

**Comment by Alfavio** [comment]
No answer after long time, so I'm closing the issue.
