### ISSUE TITLE
[Feature Request] secure delete

### ISSUE THREAD

**Issue by ray4423** [Secure-File-Manager/Secure-File-Manager#7]
I hope you add option for securely (permanently, unrecoverably) delete like "shred" linux command

thanks!

**Comment by Alfavio** [comment]
Hi @ray4423 . Thank you for the feature request! I appreciate that.

> Sanitizing storage media to reliably destroy data is an essential aspect of overall data security. We have empirically measured the effectiveness of hard drive centric sanitization techniques on flash-based SSDs. For sanitizing entire disks, built-in sanitize commands are effective when implemented correctly, and software techniques work most, but not all, of the time. **We found that none of the available software techniques for sanitizing individual files were effective**. _([source](https://www.usenix.org/legacy/events/fast11/tech/full_papers/Wei.pdf))_

So, securely wipe specific files in the filesystem is impossible on the flash memory. For secure deletion, you will need to override entire disks. The cite is from the article published in 2011, so it could have changed. If there is any technique to securely delete a specific file, please let me know. For now, I'm closing this issue.

If you have another feature request, please open a new issue.
