### ISSUE TITLE
FAQ rooted device correction

### ISSUE THREAD

**Issue by rusty-snake** [Secure-File-Manager/Secure-File-Manager#76]
https://github.com/Secure-File-Manager/Secure-File-Manager/wiki/Frequently-Asked-Questions#i-have-a-rooted-device-are-there-some-security-implications

> When an file is hidden, the file is moved from the "app-specific storage" to the "shared storage". When an file is unhidden, the file is moved from the "shared storage" to the "app-specific storage".

Shouldn't it be move from "shared storage" to "app-specific storage" for hiding?

**Comment by Alfavio** [comment]
Hi @rusty-snake. Thank you for your notice. Fixed in https://github.com/Secure-File-Manager/Secure-File-Manager/commit/4833f875b71e99ceb580159853826c08e149cb22.
