### ISSUE TITLE
Encrypt & store files in sdCard?

### ISSUE THREAD

**Issue by deep2411** [Secure-File-Manager/Secure-File-Manager#79]
![Screenshot_20230529_202526_Secure File Manager Beta.jpg](https://github.com/Secure-File-Manager/Secure-File-Manager/assets/44389527/51ebe88a-43df-49d8-a0c1-c4e2967a5774)

![Screenshot_20230529_202534_Files.jpg](https://github.com/Secure-File-Manager/Secure-File-Manager/assets/44389527/99a8219c-9d71-47f3-9800-9c638a4d5a99)

Failing to create new folder & encrypt the SDcard contents due to privacy issues.
Is there any workaround for this?

Requirement: I want to encrypt & store the encrypted files in to the SDcard & not the internal storage of the S20 FE 5G.
Thank you for the coolest application!

**Comment by Alfavio** [comment]
Hi. Unfortunately, it is not possible to encrypt & store encrypted files on the SD cart directly with the app. But, you can encrypt a file within internal memory and then move this file to the SD card.
