### ISSUE TITLE
App won't accept password

### ISSUE THREAD

**Issue by cycotcskir** [Secure-File-Manager/Secure-File-Manager#80]
Sorry if I'm not inputting this question in the right location. 

I am unable to access the app via my password. Is there a process to reset this or enter through a backdoor?

**Comment by Alfavio** [comment]
You can bypass security with these methods:

1. By installing modified app.
2. By rooting your device and accessing hidden _(not encrypted)_ files by browsing internal storage of the app. 
3. By rooting your device and bypassing authentication with [Frida](https://mas.owasp.org/MASTG/tests/android/MASVS-AUTH/MASTG-TEST-0018/#dynamic-analysis).
